### ISSUE TITLE
User Story: About us

### ISSUE THREAD

**Issue by Markpm-code** [Vasileios20/JobAppTracker#3]

**Comment by Markpm-code** [comment]
As a **User**, I can find information on the developers so that I can get in touch or view their other work

**Acceptance Criteria:**
1. A user can navigate to an about us/team profile section
2. A user can see each developer's information and social links
3. A user gets a brief description of each developer
4. As a user, I can see a resume background or image

**Tasks**
- [ ] Create an about us or team html page
- [ ] Great a UI design consistent with the current theme
- [ ] List each developer, their name, picture(with consent) a brief excerpt
- [ ] Link linkedin profiles and github profiles of each
